version: "2"
services:
  www:
    container_name: github-www
#    build: .
    image: cemborek/demo
    command: php bin/console server:run 0.0.0.0:80
    environment:
      - DB_HOST
      - DB_USER
      - DB_PASSWORD
      - DB_NAME

    ports:
      - 80:80
    restart: always
    expose:
      - 80
#    volumes:
#      - .:/var/www/html

  postgres:
    container_name: github-db
    image: postgres:9.6.2-alpine
    restart: always
    expose:
      - 5432
    ports:
      - 15432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

